// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqACgBVxrS1DzPCS-mKJBUBSdD-zegaH0',
    appId: '1:816982099717:android:467fe5a9bcae208910d96c',
    messagingSenderId: '816982099717',
    projectId: 'newsapp-69743',
    storageBucket: 'newsapp-69743.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7_XdupOOOFDXd158dGDXdgYl5pWSuDME',
    appId: '1:816982099717:ios:46940eb8c6edeccd10d96c',
    messagingSenderId: '816982099717',
    projectId: 'newsapp-69743',
    storageBucket: 'newsapp-69743.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7_XdupOOOFDXd158dGDXdgYl5pWSuDME',
    appId: '1:816982099717:ios:46940eb8c6edeccd10d96c',
    messagingSenderId: '816982099717',
    projectId: 'newsapp-69743',
    storageBucket: 'newsapp-69743.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrtpFy3nQRwd0NDOZ-P1vJjDM0lM0ncIk',
    appId: '1:816982099717:web:a0fec50fd88d7f5a10d96c',
    messagingSenderId: '816982099717',
    projectId: 'newsapp-69743',
    authDomain: 'newsapp-69743.firebaseapp.com',
    storageBucket: 'newsapp-69743.appspot.com',
    measurementId: 'G-1S2RF54D5K',
  );
}
